// This file will be auto-generated by `supabase gen types typescript --local`
// For now, we define placeholder types that match our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      clinics: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          name: string;
          slug: string;
          description: string | null;
          address: string;
          city: string;
          postal_code: string;
          province: string;
          phone: string;
          email: string | null;
          website: string | null;
          location: unknown; // PostGIS geography
          is_24h: boolean;
          has_emergency: boolean;
          is_verified: boolean;
          subscription_tier: "free" | "premium" | "pro";
          owner_id: string | null;
          logo_url: string | null;
          cover_image_url: string | null;
          rating_average: number;
          rating_count: number;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          name: string;
          slug: string;
          description?: string | null;
          address: string;
          city: string;
          postal_code: string;
          province: string;
          phone: string;
          email?: string | null;
          website?: string | null;
          location: unknown;
          is_24h?: boolean;
          has_emergency?: boolean;
          is_verified?: boolean;
          subscription_tier?: "free" | "premium" | "pro";
          owner_id?: string | null;
          logo_url?: string | null;
          cover_image_url?: string | null;
          rating_average?: number;
          rating_count?: number;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          address?: string;
          city?: string;
          postal_code?: string;
          province?: string;
          phone?: string;
          email?: string | null;
          website?: string | null;
          location?: unknown;
          is_24h?: boolean;
          has_emergency?: boolean;
          is_verified?: boolean;
          subscription_tier?: "free" | "premium" | "pro";
          owner_id?: string | null;
          logo_url?: string | null;
          cover_image_url?: string | null;
          rating_average?: number;
          rating_count?: number;
        };
        Relationships: [];
      };
      clinic_opening_hours: {
        Row: {
          id: string;
          clinic_id: string;
          day_of_week: number; // 0-6, Monday-Sunday
          opens_at: string; // TIME
          closes_at: string; // TIME
          is_closed: boolean;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          day_of_week: number;
          opens_at: string;
          closes_at: string;
          is_closed?: boolean;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          day_of_week?: number;
          opens_at?: string;
          closes_at?: string;
          is_closed?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "clinic_opening_hours_clinic_id_fkey";
            columns: ["clinic_id"];
            referencedRelation: "clinics";
            referencedColumns: ["id"];
          }
        ];
      };
      specialists: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          name: string;
          slug: string;
          title: string | null;
          bio: string | null;
          photo_url: string | null;
          avepa_specialties: string[];
          years_experience: number | null;
          is_verified: boolean;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          name: string;
          slug: string;
          title?: string | null;
          bio?: string | null;
          photo_url?: string | null;
          avepa_specialties?: string[];
          years_experience?: number | null;
          is_verified?: boolean;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          name?: string;
          slug?: string;
          title?: string | null;
          bio?: string | null;
          photo_url?: string | null;
          avepa_specialties?: string[];
          years_experience?: number | null;
          is_verified?: boolean;
        };
        Relationships: [];
      };
      clinic_specialists: {
        Row: {
          id: string;
          clinic_id: string;
          specialist_id: string;
          is_primary: boolean;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          specialist_id: string;
          is_primary?: boolean;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          specialist_id?: string;
          is_primary?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "clinic_specialists_clinic_id_fkey";
            columns: ["clinic_id"];
            referencedRelation: "clinics";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "clinic_specialists_specialist_id_fkey";
            columns: ["specialist_id"];
            referencedRelation: "specialists";
            referencedColumns: ["id"];
          }
        ];
      };
      services: {
        Row: {
          id: string;
          name: string;
          slug: string;
          category: string;
          description: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          category: string;
          description?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          category?: string;
          description?: string | null;
        };
        Relationships: [];
      };
      clinic_services: {
        Row: {
          id: string;
          clinic_id: string;
          service_id: string;
          price_min: number | null;
          price_max: number | null;
          price_visibility: "public" | "registered" | "premium";
        };
        Insert: {
          id?: string;
          clinic_id: string;
          service_id: string;
          price_min?: number | null;
          price_max?: number | null;
          price_visibility?: "public" | "registered" | "premium";
        };
        Update: {
          id?: string;
          clinic_id?: string;
          service_id?: string;
          price_min?: number | null;
          price_max?: number | null;
          price_visibility?: "public" | "registered" | "premium";
        };
        Relationships: [
          {
            foreignKeyName: "clinic_services_clinic_id_fkey";
            columns: ["clinic_id"];
            referencedRelation: "clinics";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "clinic_services_service_id_fkey";
            columns: ["service_id"];
            referencedRelation: "services";
            referencedColumns: ["id"];
          }
        ];
      };
      reviews: {
        Row: {
          id: string;
          created_at: string;
          clinic_id: string;
          user_id: string;
          rating_overall: number;
          rating_staff: number | null;
          rating_facilities: number | null;
          rating_value: number | null;
          comment: string | null;
          is_verified: boolean;
          is_approved: boolean;
        };
        Insert: {
          id?: string;
          created_at?: string;
          clinic_id: string;
          user_id: string;
          rating_overall: number;
          rating_staff?: number | null;
          rating_facilities?: number | null;
          rating_value?: number | null;
          comment?: string | null;
          is_verified?: boolean;
          is_approved?: boolean;
        };
        Update: {
          id?: string;
          created_at?: string;
          clinic_id?: string;
          user_id?: string;
          rating_overall?: number;
          rating_staff?: number | null;
          rating_facilities?: number | null;
          rating_value?: number | null;
          comment?: string | null;
          is_verified?: boolean;
          is_approved?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "reviews_clinic_id_fkey";
            columns: ["clinic_id"];
            referencedRelation: "clinics";
            referencedColumns: ["id"];
          }
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      find_nearby_clinics: {
        Args: {
          lat: number;
          lng: number;
          radius_km: number;
          emergency_only?: boolean;
        };
        Returns: {
          id: string;
          name: string;
          slug: string;
          address: string;
          city: string;
          phone: string;
          is_24h: boolean;
          has_emergency: boolean;
          distance_km: number;
        }[];
      };
      is_clinic_open_now: {
        Args: {
          clinic_id: string;
        };
        Returns: boolean;
      };
    };
    Enums: {
      subscription_tier: "free" | "premium" | "pro";
      price_visibility: "public" | "registered" | "premium";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

// Helper types
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type TablesInsert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
